packages:
  - client/*
  - client/packages/*
  - client/packages/features/*
  - packages/*
  - services/*
  - infra

catalog:
  '@aws-sdk/client-s3': ^3.1000.0
  '@babel/parser': ^7.29.0
  '@babel/traverse': ^7.29.0
  '@commitlint/cli': ^20.4.2
  '@commitlint/config-conventional': ^20.4.2
  '@commitlint/types': ^20.4.0
  '@react-email/components': ^1.0.8
  '@react-email/preview-server': ^5.2.8
  '@react-email/tailwind': ^2.0.5
  '@tailwindcss/postcss': ^4.2.1
  '@types/eslint-plugin-jsx-a11y': ^6.10.1
  '@types/jest': ^30.0.0
  '@types/node': ^25.2.3
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  aws-cdk: ^2.1106.0
  aws-cdk-lib: ^2.238.0
  aws-sdk: ^2.1693.0
  constructs: ^10.4.5
  cross-env: ^10.1.0
  dotenv: ^17.3.1
  esbuild: ^0.27.3
  eslint: ^10.0.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  husky: ^9.1.7
  jest: ^30.2.0
  prettier: ^3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  react-email: ^5.2.8
  tailwindcss: ^4.2.1
  ts-jest: ^29.4.6
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  turbo: ^2.8.10
  typescript: ^5.9.3
  typescript-eslint: ^8.55.0

overrides:
  ajv: '>=6.14.0 <7.0.0'
  conf>ajv: ^8.17.0
  esbuild: 0.27.3
  minimatch: '>=10.2.1'

patchedDependencies:
  '@commitlint/config-validator@20.4.0': patches/@commitlint__config-validator@20.4.0.patch
  '@react-email/preview-server@5.2.8': patches/@react-email__preview-server@5.2.8.patch
