-- Two changes, both driven by findings on #68 after it merged.

-- ── 1. Keep noise out of the LLM's conversation context ──────────────────
--
-- The transcript fed to the intent classifier and the field extractor is the
-- last 10 messages. Two kinds of assistant reply carry no information about the
-- user's expense and actively mislead:
--
--   * 'error'   — the static "Uy, tuve un problema procesando tu mensaje"
--   * 'unknown' — "no puedo procesar imágenes", "¿es sobre tus gastos?"
--
-- Observed in production: a session whose history contained BOTH of those had
-- its next one-word answer ("COP") classified as UNKNOWN by Nova Micro, even
-- though the prompt already carried a multi-turn rule for exactly that case.
--
-- A column rather than matching on content: 'unknown' replies are generated by
-- a model, so there is no fixed string to match, and a heuristic over prose
-- would silently rot. The flag is set at write time, where the branch is known.
--
-- These messages are still SHOWN to the user — this only removes them from the
-- model's context, so `findRecentBySession` (which restores the UI) is untouched
-- and a separate `findRecentForContext` applies the filter.

ALTER TABLE financial_management.chat_messages
  ADD COLUMN hidden_from_context boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN financial_management.chat_messages.hidden_from_context IS
  'True for assistant replies that must not reach the LLM transcript (error and unknown branches). Still rendered to the user.';

-- ── 2. Restore the index predicate 4.2.1 narrowed ────────────────────────
--
-- 4.2.1 added `expense_id IS NULL` to the partial predicate to match
-- `findLatestUnusedExtraction`. That was correct for the query AS WRITTEN, but
-- the query itself was wrong: taking "the most recent UNUSED extraction" meant
-- that retiring a newer receipt made an older abandoned one resurface and be
-- replayed into an unrelated message.
--
-- The corrected query takes the most recent extraction REGARDLESS of
-- expense_id and returns it only when unused — so it must be able to see used
-- rows, and a predicate that excludes them makes the index unusable.
--
-- `id DESC` stays: it satisfies the created_at tiebreaker.

DROP INDEX IF EXISTS financial_management.idx_chat_messages_session_extraction;

CREATE INDEX idx_chat_messages_session_extraction
  ON financial_management.chat_messages (session_id, created_at DESC, id DESC)
  WHERE attachment_extraction IS NOT NULL;
