/**
 * Generic log attribute object used as a base.
 */
type LogAttributes = {
  [key: string]: unknown;
};

/**
 * Log item extra input type.
 */
export type LogItemExtraInput = [Error | string] | LogAttributes[];

type LogAttributesWithMessage = LogAttributes & {
  /**
   * Your log message.
   */
  message: string;
  /**
   * This key is generated by the logger and cannot be set manually.
   */
  level?: never;
  /**
   * This key is generated by the logger and cannot be set manually.
   */
  sampling_rate?: never;
  /**
   * This key is generated by the logger and cannot be set manually.
   */
  service?: never;
  /**
   * This key is generated by the logger and cannot be set manually.
   */
  timestamp?: never;
};

export type LogItemMessage = string | LogAttributesWithMessage;

export abstract class LoggerService {
  abstract info(item: LogItemMessage, ...extraInput: LogItemExtraInput): void;

  abstract error(item: LogItemMessage, ...extraInput: LogItemExtraInput): void;

  abstract warn(item: LogItemMessage, ...extraInput: LogItemExtraInput): void;
}
