/**
 * Role of a chat message: who produced it.
 * - `user`: typed/uploaded by the end user.
 * - `assistant`: generated by the AI flow (Step Functions + Bedrock).
 * - `system`: internal/structural messages (rarely surfaced to the user).
 */
export type ChatMessageRole = 'user' | 'assistant' | 'system';

/**
 * Attachment kind. Reserved for Phase 2 (multimedia) but the column
 * exists from Phase 1 to keep the schema stable.
 */
export type ChatMessageAttachmentType = 'image' | 'audio';

/**
 * Lifecycle of an assistant preview that requires human confirmation
 * (Human-in-the-Loop with Step Functions Task Token).
 *
 * - `pending`: Step Function is paused waiting for the user's decision.
 * - `confirmed`: user accepted the preview; the workflow resumed.
 * - `cancelled`: user rejected the preview; the workflow resumed.
 * - `expired`: the task token timed out (Step Function timeout).
 * - `superseded`: the user iterated on the preview (sent a new message)
 *   while it was still pending, so its paused workflow was released
 *   silently and the client shows only the latest preview.
 */
export type ChatMessageTaskTokenStatus =
  | 'pending'
  | 'confirmed'
  | 'cancelled'
  | 'expired'
  | 'superseded';

/**
 * Structured data extracted from a message's attachment.
 *
 * Persisted so a follow-up turn can finish the expense WITHOUT analyzing the
 * attachment again: re-reading costs a Textract call, is rate limited (1 TPS for
 * AnalyzeExpense in us-east-2), and the raw upload is deleted after 7 days.
 *
 * Every field is optional because Textract returns only what it recognizes —
 * a blurry receipt may yield a total and nothing else.
 */
export interface ChatAttachmentExtraction {
  /** Vendor name as read from the receipt. */
  merchant?: string;
  /**
   * Total as a plain number STRING, exactly as `AnalyzedReceipt.total` produces
   * it. Kept as text rather than parsed: the value is replayed into a prompt,
   * and converting here would add a lossy step for no reader's benefit.
   */
  total?: string;
  /** ISO currency code, only when the receipt stated one. */
  currency?: string;
  /** ISO date (YYYY-MM-DD). */
  date?: string;
  /** Weakest confidence among the fields that were kept, 0-100. */
  confidence?: number;
}

/**
 * A chat message persisted in `financial_management.chat_messages`.
 */
export interface ChatMessage {
  id: string;
  session_id: string;
  role: ChatMessageRole;
  content: string;
  attachment_s3_key: string | null;
  attachment_type: ChatMessageAttachmentType | null;
  /**
   * What was read from `attachment_s3_key`. Only ever set on a message that
   * has an attachment — the database enforces that with a CHECK.
   */
  attachment_extraction: ChatAttachmentExtraction | null;
  expense_id: string | null;
  task_token: string | null;
  task_token_status: ChatMessageTaskTokenStatus | null;
  /**
   * True for replies that must NOT reach the LLM transcript — the `error` and
   * `unknown` branches. They are still shown to the user; they simply carry no
   * information about the expense and have been observed derailing intent
   * classification.
   */
  hidden_from_context: boolean;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  modified_by: string | null;
}

/**
 * Fields required to create a new chat message.
 *
 * `session_id` is mandatory (messages always live inside a session).
 * Other optional fields default to null at the DB layer.
 */
export interface CreateChatMessageInput {
  session_id: string;
  role: ChatMessageRole;
  content: string;
  attachment_s3_key?: string | null;
  attachment_type?: ChatMessageAttachmentType | null;
  expense_id?: string | null;
  task_token?: string | null;
  task_token_status?: ChatMessageTaskTokenStatus | null;
  /** Defaults to false at the DB layer. */
  hidden_from_context?: boolean;
}
