/**
 * Role of a chat message: who produced it.
 * - `user`: typed/uploaded by the end user.
 * - `assistant`: generated by the AI flow (Step Functions + Bedrock).
 * - `system`: internal/structural messages (rarely surfaced to the user).
 */
export type ChatMessageRole = 'user' | 'assistant' | 'system';

/**
 * Attachment kind. Reserved for Phase 2 (multimedia) but the column
 * exists from Phase 1 to keep the schema stable.
 */
export type ChatMessageAttachmentType = 'image' | 'audio';

/**
 * Lifecycle of an assistant preview that requires human confirmation
 * (Human-in-the-Loop with Step Functions Task Token).
 *
 * - `pending`: Step Function is paused waiting for the user's decision.
 * - `confirmed`: user accepted the preview; the workflow resumed.
 * - `cancelled`: user rejected the preview; the workflow resumed.
 * - `expired`: the task token timed out (Step Function timeout).
 */
export type ChatMessageTaskTokenStatus =
  | 'pending'
  | 'confirmed'
  | 'cancelled'
  | 'expired';

/**
 * A chat message persisted in `financial_management.chat_messages`.
 */
export interface ChatMessage {
  id: string;
  session_id: string;
  role: ChatMessageRole;
  content: string;
  attachment_s3_key: string | null;
  attachment_type: ChatMessageAttachmentType | null;
  expense_id: string | null;
  task_token: string | null;
  task_token_status: ChatMessageTaskTokenStatus | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  modified_by: string | null;
}

/**
 * Fields required to create a new chat message.
 *
 * `session_id` is mandatory (messages always live inside a session).
 * Other optional fields default to null at the DB layer.
 */
export interface CreateChatMessageInput {
  session_id: string;
  role: ChatMessageRole;
  content: string;
  attachment_s3_key?: string | null;
  attachment_type?: ChatMessageAttachmentType | null;
  expense_id?: string | null;
  task_token?: string | null;
  task_token_status?: ChatMessageTaskTokenStatus | null;
}
